SELECT*
FROM PortfolioProject..CovidDeaths$
ORDER BY 3,4

SELECT *
FROM PortfolioProject..CovidVaccinations$
ORDER BY 3,4

-- SELECT DATA THAT WE ARE GOING TO BE USING
SELECT LOCATION,DATE,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,POPULATION
FROM PortfolioProject..CovidDeaths$
ORDER BY 1,2

--LOOKING AT TOTAL CASES VS TOTAL DEATHS IN INDONESIA
SELECT LOCATION,DATE,TOTAL_CASES,TOTAL_DEATHS,(total_cases/total_deaths)*100 DEATHPERCENTAGE
FROM PortfolioProject..CovidDeaths$
WHERE location LIKE '%INDONESIA%'
ORDER BY 1,2

--LOOKING AT TOTAL CASES VS POPULATION IN INDONESIA
SELECT LOCATION,DATE,population,total_cases,(total_cases/population)*100 PERCENTPOPULATIONINFECTED
FROM PortfolioProject..CovidDeaths$
WHERE location LIKE '%INDONESIA%'
ORDER BY 1,2

--LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION
SELECT LOCATION,population,MAX(total_cases) AS HIGHESTINFECTION,MAX((total_cases/population))*100  AS PERCENTPOPULATIONINFECTED
FROM PortfolioProject..CovidDeaths$
GROUP BY LOCATION, population
ORDER BY PERCENTPOPULATIONINFECTED DESC

--SHOWING COUNTINET WITH HIGHEST DEATH COUNT PER POPULATION
SELECT continent,POPULATION,MAX(CAST( TOTAL_DEATHS AS INT)) AS TOTALDEATHSCOUNT
FROM PortfolioProject..CovidDeaths$
WHERE continent IS NOT NULL
GROUP BY continent,population
ORDER BY TOTALDEATHSCOUNT DESC

--GLOBAL NUMBERS
SELECT DATE,SUM(NEW_CASES) AS TOTALCASES,SUM(CAST(NEW_DEATHS AS INT)) AS TOTALDEATHS,SUM(NEW_CASES)/SUM(CAST(NEW_DEATHS AS INT))*100 AS DEATHPERCENTAGE
FROM PortfolioProject..CovidDeaths$
WHERE continent IS NOT NULL
GROUP BY DATE
ORDER BY 1,2

--LOOKING AT TOTAL POPULATION VS VACCINATION
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations
,SUM(CAST(VAC.new_vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..CovidDeaths$ DEA
INNER JOIN PortfolioProject..CovidVaccinations$ VAC
ON DEA.location = VAC.location
AND DEA.date = VAC.date
WHERE DEA.continent IS NOT NULL
ORDER BY 2,3

--USE CTE 
WITH POPVSVAC (CONTINENT,LOCATION,DATE,POPULATION,NEW_VACCINATIONS,ROLLINGPEOPLEVACCINATED)
AS
(
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations
,SUM(CAST(VAC.new_vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..CovidDeaths$ DEA
INNER JOIN PortfolioProject..CovidVaccinations$ VAC
ON DEA.location = VAC.location
AND DEA.date = VAC.date
WHERE DEA.continent IS NOT NULL
)
SELECT*, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM POPVSVAC

-- TEMP TABLE
DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
ROLLINGPEOPLEVACCINATED NUMERIC
)
INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations
,SUM(CAST(VAC.new_vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..CovidDeaths$ DEA
INNER JOIN PortfolioProject..CovidVaccinations$ VAC
ON DEA.location = VAC.location
AND DEA.date = VAC.date
WHERE DEA.continent IS NOT NULL
SELECT*, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM #PERCENTPOPULATIONVACCINATED

--CREATE VIEW
CREATE VIEW PERCERNTPOPULATIONVACCINATED AS
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations
,SUM(CAST(VAC.new_vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PortfolioProject..CovidDeaths$ DEA
INNER JOIN PortfolioProject..CovidVaccinations$ VAC
ON DEA.location = VAC.location
AND DEA.date = VAC.date
WHERE DEA.continent IS NOT NULL

SELECT *
FROM PERCERNTPOPULATIONVACCINATED

